# Enable shadows
shadow = true;

# Set shadow properties
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.7;

# Exclude specific windows from having shadows
shadow-exclude = [
    "class_g = 'qtile'",
    "class_g = 'Polybar'"
];

# Fade in and out
fading = true;
fade-delta = 12;
fade-in-step = 0.1;
fade-out-step = 0.1;

# Other settings
backend = "glx";
vsync = true;
corner-radius = 10

active-opacity = 1
inactive-opacity = 0.9
opacity-rule = [
"100:name *= 'Firefox'",
"100:name *= 'nvim'",
"100:name *= 'Code'",
"100:name *= 'Midori'",

]
blur-method = "dual_kawase"
blur-size = 12
#
# blur-deviation = false
#
blur-strength = 5

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
"class_g = 'firefox'"
];
