--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bnsplit/Images/Wallpapers/590 390.jpg"

-- Special
background="#0E0703"
foreground="#cee1ed"
cursor="#cee1ed"

-- Colors
color0="#0E0703"
color1="#A15115"
color2="#D45F05"
color3="#907356"
color4="#F68D0C"
color5="#D5C469"
color6="#6E8F94"
color7="#cee1ed"
color8="#909da5"
color9="#A15115"
color10="#D45F05"
color11="#907356"
color12="#F68D0C"
color13="#D5C469"
color14="#6E8F94"
color15="#cee1ed"
