# Shell variables
# Generated by 'wal'
wallpaper='/home/bnsplit/Images/Wallpapers/590 390.jpg'

# Special
background='#0E0703'
foreground='#cee1ed'
cursor='#cee1ed'

# Colors
color0='#0E0703'
color1='#A15115'
color2='#D45F05'
color3='#907356'
color4='#F68D0C'
color5='#D5C469'
color6='#6E8F94'
color7='#cee1ed'
color8='#909da5'
color9='#A15115'
color10='#D45F05'
color11='#907356'
color12='#F68D0C'
color13='#D5C469'
color14='#6E8F94'
color15='#cee1ed'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
