--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bnsplit/Images/Wallpapers/3 459 455.jpg"

-- Special
background="#0e0d12"
foreground="#c2c2c3"
cursor="#c2c2c3"

-- Colors
color0="#0e0d12"
color1="#12748B"
color2="#407496"
color3="#2191A6"
color4="#59A5B4"
color5="#64B6CA"
color6="#A8BDAA"
color7="#c2c2c3"
color8="#5f586c"
color9="#12748B"
color10="#407496"
color11="#2191A6"
color12="#59A5B4"
color13="#64B6CA"
color14="#A8BDAA"
color15="#c2c2c3"
