--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bnsplit/Images/Wallpapers/2 368 398.jpg"

-- Special
background="#0A0A08"
foreground="#c1c1c1"
cursor="#c1c1c1"

-- Colors
color0="#0A0A08"
color1="#9A1C13"
color2="#E51308"
color3="#B9593B"
color4="#D29453"
color5="#3853AD"
color6="#1B62D3"
color7="#c1c1c1"
color8="#676755"
color9="#9A1C13"
color10="#E51308"
color11="#B9593B"
color12="#D29453"
color13="#3853AD"
color14="#1B62D3"
color15="#c1c1c1"
