# Shell variables
# Generated by 'wal'
wallpaper="/home/bnsplit/Images/Wallpapers/2 368 398.jpg"

# Special
background='#0A0A08'
foreground='#c1c1c1'
cursor='#c1c1c1'

# Colors
color0='#0A0A08'
color1='#9A1C13'
color2='#E51308'
color3='#B9593B'
color4='#D29453'
color5='#3853AD'
color6='#1B62D3'
color7='#c1c1c1'
color8='#676755'
color9='#9A1C13'
color10='#E51308'
color11='#B9593B'
color12='#D29453'
color13='#3853AD'
color14='#1B62D3'
color15='#c1c1c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
