[colors.primary]
background = "#16180d"
foreground = "#c4c5c2"

[colors.cursor]
text = "#16180d"
cursor = "#c4c5c2"

[colors.vi_mode_cursor]
text = "#16180d"
cursor = "#c4c5c2"

[colors.search.matches]
foreground = "#16180d"
background = "#c4c5c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6b6e5a"
background = "#c4c5c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#16180d"
red = "#96673C"
green = "#77846F"
yellow = "#A18F72"
blue = "#CF974C"
magenta = "#B3A58A"
cyan = "#CBB595"
white = "#c4c5c2"

[colors.bright]
black = "#6b6e5a"
red = "#96673C"
green = "#77846F"
yellow = "#A18F72"
blue = "#CF974C"
magenta = "#B3A58A"
cyan = "#CBB595"
white = "#c4c5c2"

[colors.dim]
black = "#c4c5c2"
red = "#96673C"
green = "#B3A58A"
yellow = "#A18F72"
blue = "#CF974C"
magenta = "#77846F"
cyan = "#CBB595"
white = "#6b6e5a"

