--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bnsplit/Pictures/Wallpapers/013.jpg"

-- Special
background="#180f0d"
foreground="#f9d6cc"
cursor="#f1dfda"

-- Colors
color0="#180f0d"
color1="#e78a73"
color2="#9eae9b"
color3="#79c1a0"
color4="#eaa778"
color5="#e1b77e"
color6="#d8ebb2"
color7="#f3e6c6"
color8="#caaca4"
color9="#ec9a86"
color10="#abb8a8"
color11="#8cc9ad"
color12="#edb28b"
color13="#e5c090"
color14="#ddedbd"
color15="#f4e9ce"
