--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bnsplit/Images/Wallpapers/008.png"

-- Special
background="#0e1013"
foreground="#c2c3c4"
cursor="#c2c3c4"

-- Colors
color0="#0e1013"
color1="#665C54"
color2="#70655B"
color3="#766E61"
color4="#BE492A"
color5="#867667"
color6="#64A66C"
color7="#c2c3c4"
color8="#59606d"
color9="#665C54"
color10="#70655B"
color11="#766E61"
color12="#BE492A"
color13="#867667"
color14="#64A66C"
color15="#c2c3c4"
