[colors.primary]
background = "#020209"
foreground = "#bfbfc1"

[colors.cursor]
text = "#020209"
cursor = "#bfbfc1"

[colors.vi_mode_cursor]
text = "#020209"
cursor = "#bfbfc1"

[colors.search.matches]
foreground = "#020209"
background = "#bfbfc1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#535365"
background = "#bfbfc1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#020209"
red = "#A42621"
green = "#EA1608"
yellow = "#DD2014"
blue = "#EC5829"
magenta = "#BE9771"
cyan = "#719591"
white = "#bfbfc1"

[colors.bright]
black = "#535365"
red = "#A42621"
green = "#EA1608"
yellow = "#DD2014"
blue = "#EC5829"
magenta = "#BE9771"
cyan = "#719591"
white = "#bfbfc1"

[colors.dim]
black = "#bfbfc1"
red = "#A42621"
green = "#BE9771"
yellow = "#DD2014"
blue = "#EC5829"
magenta = "#EA1608"
cyan = "#719591"
white = "#535365"

