# Shell variables
# Generated by 'wal'
wallpaper='/home/bnsplit/Pictures/Wallpapers/018.png'

# Special
background='#111418'
foreground='#d2ddf2'
cursor='#e1e2e8'

# Colors
color0='#111418'
color1='#af9ffe'
color2='#7ab6f8'
color3='#7ec0de'
color4='#dfa6ef'
color5='#edb686'
color6='#f6bbc5'
color7='#c2dad8'
color8='#a9b4c5'
color9='#b9acff'
color10='#8cc0f9'
color11='#91c9e3'
color12='#e3b2f2'
color13='#f0c097'
color14='#f7c3cd'
color15='#cadedd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
