[colors.primary]
background = "#120d16"
foreground = "#c3c2c4"

[colors.cursor]
text = "#120d16"
cursor = "#c3c2c4"

[colors.vi_mode_cursor]
text = "#120d16"
cursor = "#c3c2c4"

[colors.search.matches]
foreground = "#120d16"
background = "#c3c2c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#63596e"
background = "#c3c2c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#120d16"
red = "#254EA3"
green = "#3452AA"
yellow = "#505EAD"
blue = "#6174C3"
magenta = "#877AB4"
cyan = "#CBADBA"
white = "#c3c2c4"

[colors.bright]
black = "#63596e"
red = "#254EA3"
green = "#3452AA"
yellow = "#505EAD"
blue = "#6174C3"
magenta = "#877AB4"
cyan = "#CBADBA"
white = "#c3c2c4"

[colors.dim]
black = "#c3c2c4"
red = "#254EA3"
green = "#877AB4"
yellow = "#505EAD"
blue = "#6174C3"
magenta = "#3452AA"
cyan = "#CBADBA"
white = "#63596e"

