[colors.primary]
background = "#1e0804"
foreground = "#c6c1c0"

[colors.cursor]
text = "#1e0804"
cursor = "#c6c1c0"

[colors.vi_mode_cursor]
text = "#1e0804"
cursor = "#c6c1c0"

[colors.search.matches]
foreground = "#1e0804"
background = "#c6c1c0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6d5d59"
background = "#c6c1c0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1e0804"
red = "#956754"
green = "#17946E"
yellow = "#AA8C6D"
blue = "#DE9965"
magenta = "#44A387"
cyan = "#BAA190"
white = "#c6c1c0"

[colors.bright]
black = "#6d5d59"
red = "#956754"
green = "#17946E"
yellow = "#AA8C6D"
blue = "#DE9965"
magenta = "#44A387"
cyan = "#BAA190"
white = "#c6c1c0"

[colors.dim]
black = "#c6c1c0"
red = "#956754"
green = "#44A387"
yellow = "#AA8C6D"
blue = "#DE9965"
magenta = "#17946E"
cyan = "#BAA190"
white = "#6d5d59"

