--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bnsplit/Pictures/Wallpapers/038.jpg"

-- Special
background="#101510"
foreground="#cde2ce"
cursor="#dfe4dc"

-- Colors
color0="#101510"
color1="#95adfc"
color2="#8fbbf8"
color3="#88d39b"
color4="#8ccbf5"
color5="#9cdee9"
color6="#97e5c3"
color7="#a3f2e5"
color8="#a5b8a6"
color9="#a2b8fc"
color10="#9dc4f9"
color11="#98d9a7"
color12="#9cd2f6"
color13="#aae2eb"
color14="#a5e8ca"
color15="#b0f4e7"
