--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bnsplit/Images/Wallpapers/073.png"

-- Special
background="#0d0705"
foreground="#c2c1c0"
cursor="#c2c1c0"

-- Colors
color0="#0d0705"
color1="#5F5027"
color2="#344B43"
color3="#525253"
color4="#8E3616"
color5="#9F5519"
color6="#BF6B2D"
color7="#c2c1c0"
color8="#675855"
color9="#5F5027"
color10="#344B43"
color11="#525253"
color12="#8E3616"
color13="#9F5519"
color14="#BF6B2D"
color15="#c2c1c0"
