--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bnsplit/Images/Wallpapers/056.jpg"

-- Special
background="#120d16"
foreground="#c3c2c4"
cursor="#c3c2c4"

-- Colors
color0="#120d16"
color1="#254EA3"
color2="#3452AA"
color3="#505EAD"
color4="#6174C3"
color5="#877AB4"
color6="#CBADBA"
color7="#c3c2c4"
color8="#63596e"
color9="#254EA3"
color10="#3452AA"
color11="#505EAD"
color12="#6174C3"
color13="#877AB4"
color14="#CBADBA"
color15="#c3c2c4"
