[colors.primary]
background = "#0d1215"
foreground = "#c2c3c4"

[colors.cursor]
text = "#0d1215"
cursor = "#c2c3c4"

[colors.vi_mode_cursor]
text = "#0d1215"
cursor = "#c2c3c4"

[colors.search.matches]
foreground = "#0d1215"
background = "#c2c3c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59656d"
background = "#c2c3c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0d1215"
red = "#4F6467"
green = "#6E827A"
yellow = "#1F728C"
blue = "#497595"
magenta = "#2B93AA"
cyan = "#49AABE"
white = "#c2c3c4"

[colors.bright]
black = "#59656d"
red = "#4F6467"
green = "#6E827A"
yellow = "#1F728C"
blue = "#497595"
magenta = "#2B93AA"
cyan = "#49AABE"
white = "#c2c3c4"

[colors.dim]
black = "#c2c3c4"
red = "#4F6467"
green = "#2B93AA"
yellow = "#1F728C"
blue = "#497595"
magenta = "#6E827A"
cyan = "#49AABE"
white = "#59656d"

