# Shell variables
# Generated by 'wal'
wallpaper='/home/bnsplit/Pictures/Wallpapers/25.png'

# Special
background='#180f0e'
foreground='#f9d5cf'
cursor='#f1dfdb'

# Colors
color0='#180f0e'
color1='#fb7e6c'
color2='#ff7d97'
color3='#d88aff'
color4='#ff86e1'
color5='#ffa776'
color6='#febf7a'
color7='#f9ef8b'
color8='#caaba6'
color9='#fe9080'
color10='#ff8fa5'
color11='#de9aff'
color12='#ff97e5'
color13='#ffb38a'
color14='#ffc88e'
color15='#faf19d'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
