[colors.primary]
background = "#080E14"
foreground = "#c1c2c4"

[colors.cursor]
text = "#080E14"
cursor = "#c1c2c4"

[colors.vi_mode_cursor]
text = "#080E14"
cursor = "#c1c2c4"

[colors.search.matches]
foreground = "#080E14"
background = "#c1c2c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#58616b"
background = "#c1c2c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#080E14"
red = "#4D6466"
green = "#41953A"
yellow = "#369561"
blue = "#4FA063"
magenta = "#74AC7B"
cyan = "#5ECB63"
white = "#c1c2c4"

[colors.bright]
black = "#58616b"
red = "#4D6466"
green = "#41953A"
yellow = "#369561"
blue = "#4FA063"
magenta = "#74AC7B"
cyan = "#5ECB63"
white = "#c1c2c4"

[colors.dim]
black = "#c1c2c4"
red = "#4D6466"
green = "#74AC7B"
yellow = "#369561"
blue = "#4FA063"
magenta = "#41953A"
cyan = "#5ECB63"
white = "#58616b"

