# Shell variables
# Generated by 'wal'
wallpaper="/home/bnsplit/Images/Wallpapers/050.jpg"

# Special
background='#080E14'
foreground='#c1c2c4'
cursor='#c1c2c4'

# Colors
color0='#080E14'
color1='#4D6466'
color2='#41953A'
color3='#369561'
color4='#4FA063'
color5='#74AC7B'
color6='#5ECB63'
color7='#c1c2c4'
color8='#58616b'
color9='#4D6466'
color10='#41953A'
color11='#369561'
color12='#4FA063'
color13='#74AC7B'
color14='#5ECB63'
color15='#c1c2c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
