[colors.primary]
background = "#191918"
foreground = "#c5c5c5"

[colors.cursor]
text = "#191918"
cursor = "#c5c5c5"

[colors.vi_mode_cursor]
text = "#191918"
cursor = "#c5c5c5"

[colors.search.matches]
foreground = "#191918"
background = "#c5c5c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#72725e"
background = "#c5c5c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#191918"
red = "#A89071"
green = "#B46C87"
yellow = "#568C89"
blue = "#A0A390"
magenta = "#D29E98"
cyan = "#B7C5A6"
white = "#c5c5c5"

[colors.bright]
black = "#72725e"
red = "#A89071"
green = "#B46C87"
yellow = "#568C89"
blue = "#A0A390"
magenta = "#D29E98"
cyan = "#B7C5A6"
white = "#c5c5c5"

[colors.dim]
black = "#c5c5c5"
red = "#A89071"
green = "#D29E98"
yellow = "#568C89"
blue = "#A0A390"
magenta = "#B46C87"
cyan = "#B7C5A6"
white = "#72725e"

