[colors.primary]
background = "#0B1011"
foreground = "#c2c3c3"

[colors.cursor]
text = "#0B1011"
cursor = "#c2c3c3"

[colors.vi_mode_cursor]
text = "#0B1011"
cursor = "#c2c3c3"

[colors.search.matches]
foreground = "#0B1011"
background = "#c2c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#58666b"
background = "#c2c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0B1011"
red = "#324A2F"
green = "#545233"
yellow = "#2D3944"
blue = "#37484D"
magenta = "#5A5C54"
cyan = "#817951"
white = "#c2c3c3"

[colors.bright]
black = "#58666b"
red = "#324A2F"
green = "#545233"
yellow = "#2D3944"
blue = "#37484D"
magenta = "#5A5C54"
cyan = "#817951"
white = "#c2c3c3"

[colors.dim]
black = "#c2c3c3"
red = "#324A2F"
green = "#5A5C54"
yellow = "#2D3944"
blue = "#37484D"
magenta = "#545233"
cyan = "#817951"
white = "#58666b"

