--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bnsplit/Images/Wallpapers/116.png"

-- Special
background="#0d1215"
foreground="#c2c3c4"
cursor="#c2c3c4"

-- Colors
color0="#0d1215"
color1="#4F6467"
color2="#6E827A"
color3="#1F728C"
color4="#497595"
color5="#2B93AA"
color6="#49AABE"
color7="#c2c3c4"
color8="#59656d"
color9="#4F6467"
color10="#6E827A"
color11="#1F728C"
color12="#497595"
color13="#2B93AA"
color14="#49AABE"
color15="#c2c3c4"
