[colors.primary]
background = "#0d0705"
foreground = "#c2c1c0"

[colors.cursor]
text = "#0d0705"
cursor = "#c2c1c0"

[colors.vi_mode_cursor]
text = "#0d0705"
cursor = "#c2c1c0"

[colors.search.matches]
foreground = "#0d0705"
background = "#c2c1c0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#675855"
background = "#c2c1c0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0d0705"
red = "#5F5027"
green = "#344B43"
yellow = "#525253"
blue = "#8E3616"
magenta = "#9F5519"
cyan = "#BF6B2D"
white = "#c2c1c0"

[colors.bright]
black = "#675855"
red = "#5F5027"
green = "#344B43"
yellow = "#525253"
blue = "#8E3616"
magenta = "#9F5519"
cyan = "#BF6B2D"
white = "#c2c1c0"

[colors.dim]
black = "#c2c1c0"
red = "#5F5027"
green = "#9F5519"
yellow = "#525253"
blue = "#8E3616"
magenta = "#344B43"
cyan = "#BF6B2D"
white = "#675855"

