[colors.primary]
background = "#0d0d0d"
foreground = "#c2c2c2"

[colors.cursor]
text = "#0d0d0d"
cursor = "#c2c2c2"

[colors.vi_mode_cursor]
text = "#0d0d0d"
cursor = "#c2c2c2"

[colors.search.matches]
foreground = "#0d0d0d"
background = "#c2c2c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6a5757"
background = "#c2c2c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0d0d0d"
red = "#605555"
green = "#9A0E1E"
yellow = "#A70F1E"
blue = "#A51C29"
magenta = "#CC4A58"
cyan = "#CA8E6C"
white = "#c2c2c2"

[colors.bright]
black = "#6a5757"
red = "#605555"
green = "#9A0E1E"
yellow = "#A70F1E"
blue = "#A51C29"
magenta = "#CC4A58"
cyan = "#CA8E6C"
white = "#c2c2c2"

[colors.dim]
black = "#c2c2c2"
red = "#605555"
green = "#CC4A58"
yellow = "#A70F1E"
blue = "#A51C29"
magenta = "#9A0E1E"
cyan = "#CA8E6C"
white = "#6a5757"

